Unify config loading and NSS default db type
The inclusion of pki.conf shell snippets and handling of
NSS_DEFAULT_DB_TYPE env var is now simplified and unified. The default
DB type is no longer a user modifyable setting. The selection of NSS DB
type is platform and release specific. The value is controlled by the
CMake flag PKI_NSS_DB_TYPE.

All shell scripts source a common /usr/share/pki/scripts/config file.
The config file loads default, system-wide, and user pki.conf. It also
ensures that NSS_DEFAULT_DB_TYPE is set correctly. Now all scripts support
~/.dogtag/pki.conf, too.

Tomcat services load a default tomcat.conf environment file from
/usr/share/pki/etc/, which sets NSS_DEFAULT_DB_TYPE for pki-tomcatd and
pki-tomcatd-nuxwdog.

Change-Id: I36fc28e9098de9db9f81a1dfd521292b27d57550
Signed-off-by: Christian Heimes <cheimes@redhat.com>

diff --git a/base/common/scripts/config b/base/common/scripts/config
--- a/base/common/scripts/config
+++ b/base/common/scripts/config
@@ -1,4 +1,3 @@
-#!/bin/sh
 #
 # --- BEGIN COPYRIGHT BLOCK ---
 # This program is free software; you can redistribute it and/or modify
@@ -14,15 +13,35 @@
 # with this program; if not, write to the Free Software Foundation, Inc.,
 # 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 #
-# Copyright (C) 2017 Red Hat, Inc.
+# Copyright (C) 2018 Red Hat, Inc.
 # All rights reserved.
 # --- END COPYRIGHT BLOCK ---
 #
 
-# load default, system-wide, and user-specific PKI configuration and
-# set NSS_DEFAULT_DB_TYPE.
-. /usr/share/pki/scripts/config
+# default PKI configuration
+. /usr/share/pki/etc/pki.conf
 
-@PYTHON_EXECUTABLE@ -m pki.cli.main "$@"
+# safe NSS_DEFAULT_DB_TYPE
+_PKI_NSS_DEFAULT_DB_TYPE=${NSS_DEFAULT_DB_TYPE}
 
-exit $?
+# system-wide PKI configuration
+if [ -f /etc/pki/pki.conf ]
+then
+    . /etc/pki/pki.conf
+fi
+
+# user-specific PKI configuration
+if [ -f $HOME/.dogtag/pki.conf ]
+then
+    . $HOME/.dogtag/pki.conf
+fi
+
+# set and verify NSS_DEFAULT_DB_TYPE
+export NSS_DEFAULT_DB_TYPE=${_PKI_NSS_DEFAULT_DB_TYPE}
+case ${NSS_DEFAULT_DB_TYPE} in
+    dbm|sql)
+        break;;
+    *)
+        echo "ERROR: Unsupported NSS_DEFAULT_DB_TYPE=${NSS_DEFAULT_DB_TYPE}"
+        exit 1;;
+esac
