Bug 810967 - [RFE] ECC support for pkisilent

diff --git a/base/silent/templates/silentEC_subca.template b/base/silent/templates/silentEC_subca.template
--- a/base/silent/templates/silentEC_subca.template
+++ b/base/silent/templates/silentEC_subca.template
@@ -1,6 +1,6 @@
 #!/bin/bash
 ##  BEGIN COPYRIGHT BLOCK
-##  (C) 2009 Red Hat, Inc.
+##  (C) 2013 Red Hat, Inc.
 ##  All rights reserved.
 ##  END COPYRIGHT BLOCK
 
@@ -13,8 +13,13 @@ cd `dirname $0`
 
 
 ##  Disallow script to be run as the name of this template
-subca_silent_script=`basename $0`
-if	[ "${subca_silent_script}" = "subca_silent.template" ] ; then
+subca_silentEC_script=`basename $0`
+if	[ "${subca_silentEC_script}" = "silentEC_subca.template" ] ; then
+	printf "\n"
+	printf "Important:  Use the following reference for essential EC setup\n"
+	printf "            prior to running this script:\n"
+	printf "\n"
+	printf "                silentEC_readme.txt.\n\n"
 	printf "\n"
 	printf "Usage:  (1) Install AND configure a directory server instance.\n\n"
 	printf "        (2) Install AND configure a Root CA subsystem instance\n"
@@ -22,22 +27,24 @@ if	[ "${subca_silent_script}" = "subca_silent.template" ] ; then
 	printf "        (3) Use 'pkicreate' to install a second CA subsystem\n"
 	printf "            instance (this will become a Subordinate CA).\n"
 	printf "            [Do NOT configure this CA subsystem instance!]\n\n"
+	printf "            Follow ECC setup instruction in silentEC_readme.txt.\n"
 	printf "        (4) Install the 'pki-silent' package.\n\n"
 	printf "        (5) Copy '$0' to a new script name\n"
 	printf "            without the '.template' extension.\n"
-	printf "            (e .g. - 'configure_subca_instance')\n\n"
+	printf "            (e .g. - 'configure_ec_subca_instance')\n\n"
 	printf "        (6) Fill in all MANDATORY user-defined variables\n"
 	printf "            in the new script.\n\n"
 	printf "        (7) Change any OPTIONAL user-defined variables\n"
 	printf "            in the new script as desired.\n\n"
-	printf "        (8) Become the 'root' user, and execute the new script to\n"
+	printf "        (8) Become the subca administrator user (NOT 'root' user),\n"
+	printf "            and execute the new script to\n"
 	printf "            configure a Subordinate CA subsystem instance.\n\n"
 	exit 255
 fi
 
 
 ##
-##  This script MUST be run as root!
+##  This script should not be run as root!
 ##
 
 ROOTUID=0
@@ -52,9 +59,9 @@ else
 	exit 255
 fi
 
-if	[ "${MY_UID}"  != "${ROOTUID}" ] &&
-	[ "${MY_EUID}" != "${ROOTUID}" ] ; then
-	printf "ERROR:  The '$0' script must be run as root!\n"
+if	[ "${MY_UID}"  == "${ROOTUID}" ] ||
+	[ "${MY_EUID}" == "${ROOTUID}" ] ; then
+	printf "ERROR:  The '$0' script should not be run as root!\n"
 	exit 255
 fi
 
@@ -82,12 +89,22 @@ fi
 
 ##  PKI Silent Security Database Variables
 ##  (e. g. - PKI Silent "browser" database)
-pki_silent_security_database_repository="/tmp"
+##  See "silentEC_readme.txt" for instruction on "Browser"
+##  Once Firefox is set up for EC, the following 
+##  pki_silent_security_database_repository
+##  parameter should be set to ~/.mozilla/firefox/<your new profile directory>
+##  Example:
+##pki_silent_security_database_repository="/home/jdoe/.mozilla/firefox/u7bdq5th.silent"
+##pki_silent_security_database_password="mypasswd"
+##pki_silent_security_token_name="Certicom\ FIPS\ Cert/Key\ Services"
+pki_silent_security_database_repository=
 pki_silent_security_database_password=
-pki_silent_security_token_name=internal
+pki_silent_security_token_name=
 
 ##  PKI Security Domain Variables
 ##  (e. g. - Security Domain Login Panel)
+## Example:
+##pki_security_domain_name="sample\ ECC\ domain"
 pki_security_domain_name=
 pki_security_domain_host=`hostname`
 pki_security_domain_admin_name=admin
@@ -102,12 +119,19 @@ pki_bind_password=
 
 ##  PKI Instance-Specific Token Variables
 ##  (e. g. - Module Panel)
-subca_token_name=internal
+## ECC subsystems in general are set up with an HSM.
+## Example:
+##subca_token_name=NHSM6000-OCS
+##subca_token_password=hsmpasswd
+subca_token_name=
 subca_token_password=
 
 ##  PKI Instance-Specific Backup Variables
 ##  (e. g. - Backup Key and Certificates Panel)
-subca_backup_password=
+##  Note: in an ECC setup, you will most likely hook up the CS subsystems
+##  with an HSM, so the keys cannot be backed up in this software fashion
+##  so it's irrelevant
+subca_backup_password=redhat
 
 ##  PKI Email Variables
 ##
@@ -123,7 +147,7 @@ pki_email_domain=
 
 ##  PKI Silent Admin Variables
 ##  (e. g. - Import Admin Certificate into PKI Silent "browser" database)
-pki_silent_admin_user=admin
+pki_silent_admin_user=
 pki_silent_admin_password=
 pki_silent_admin_email="${pki_email_name}\@${pki_email_company}\.${pki_email_domain}"
 
@@ -137,13 +161,14 @@ pki_silent_admin_email="${pki_email_name}\@${pki_email_company}\.${pki_email_dom
 pki_host=`hostname`
 
 ##  PKI Subsystem Names
-ca_subsystem_name="Certificate\ Authority"
+## Example:
+#subca_subsystem_name="Certificate\ Authority\ EC\ 2"
+subca_subsystem_name=
 
 ##  PKI Subsystem Instance Names
-subca_instance_name="pki-subca"
-
-##  PKI Subsystem Init Script Names
-subca_init_script="pki-cad"
+## Example:
+##subca_instance_name="pki-subca-EC"
+subca_instance_name=
 
 ##
 ##  NOTE:  Default PKI Instance Ports
@@ -162,7 +187,7 @@ subca_init_script="pki-cad"
 ##      semanage port -l | grep pki
 ##
 ##      pki_ca_port_t          tcp      9180, 9701, 9443, 9444, 9445
-##      pki_subca_port_t       tcp      9580, 9801, 9543, 9544, 9545
+##      pki_ca1_port_t         tcp      9580, 9801, 9543, 9544, 9545
 ##
 
 ## CA ports
@@ -184,8 +209,7 @@ subca_admin_port=9545
 ##############################################################################
 
 ##  PKI Silent Log Files
-pki_silent_subca_log=/tmp/subca.log
-
+pki_silent_subca_log=${pki_silent_security_database_repository}/subcaEC.log
 
 ##
 ## NOTE:  For comparison's sake, if the default instances were manually
@@ -252,6 +276,7 @@ pki_silent_subca_log=/tmp/subca.log
 ##
 ##                 Nickname:  "caSigningCert cert-${subca_instance_name}"
 ##             Subject Name:  "cn=Certificate Authority 2,"
+##                         +  "ou=${subca_instance_name},"
 ##                         +  "o=${pki_security_domain_name}"
 ##
 ##                 Nickname:  "Server-Cert cert-${subca_instance_name}"
@@ -261,18 +286,22 @@ pki_silent_subca_log=/tmp/subca.log
 ##                 Nickname:  "Certificate Authority - "
 ##                         +  "${pki_security_domain_name}"
 ##             Subject Name:  "cn=Certificate Authority,"
+##                         +  "ou=${ca_instance_name},"
 ##                         +  "o=${pki_security_domain_name}"
 ##
 ##                 Nickname:  "ocspSigningCert cert-${subca_instance_name}"
 ##             Subject Name:  "cn=OCSP Signing Certificate 2,"
+##                         +  "ou=${subca_instance_name},"
 ##                         +  "o=${pki_security_domain_name}"
 ##
 ##                 Nickname:  "auditSigningCert cert-${subca_instance_name}"
 ##             Subject Name:  "cn=CA Audit Signing Certificate 2,"
+##                         +  "ou=${subca_instance_name},"
 ##                         +  "o=${pki_security_domain_name}"
 ##
 ##                 Nickname:  "subsystemCert cert-${subca_instance_name}"
 ##             Subject Name:  "cn=CA Subsystem Certificate 2,"
+##                         +  "ou=${subca_instance_name},"
 ##                         +  "o=${pki_security_domain_name}"
 ##
 ##  NOTE:  The parameters for the signing algorithms have the following meaning:
@@ -282,22 +311,35 @@ pki_silent_subca_log=/tmp/subca.log
 ##
 
 subca_agent_name="CA\ Administrator\ of\ Instance\ ${subca_instance_name}\'s\ ${pki_security_domain_name}\ ID"
-subca_agent_key_size=2048
-subca_agent_key_type=rsa
+subca_agent_key_size=nistp256
+subca_agent_key_type=ecc
 subca_agent_cert_subject="cn=CA\ Administrator\ of\ Instance\ ${subca_instance_name},uid=admin,e=${pki_silent_admin_email},o=${pki_security_domain_name}"
 subca_base_dn="dc=${pki_host}-${subca_instance_name}"
 subca_db_name="${pki_host}-${subca_instance_name}"
-subca_key_size=2048
-subca_key_type=rsa
-subca_signing_algorithm=SHA256withRSA
-subca_signing_signingalgorithm=SHA256withRSA
-subca_ocsp_signing_signingalgorithm=SHA256withRSA
-subca_sign_cert_subject_name="cn=Certificate\ Authority\ 2,o=${pki_security_domain_name}"
-subca_subsystem_cert_subject_name="cn=CA\ Subsystem\ Certificate\ 2,o=${pki_security_domain_name}"
-subca_ocsp_cert_subject_name="cn=OCSP\ Signing\ Certificate\ 2,o=${pki_security_domain_name}"
-subca_server_cert_subject_name="cn=${pki_host},o=${pki_security_domain_name}"
-subca_audit_signing_cert_subject_name="cn=CA\ Audit\ Signing\ Certificate\ 2,o=${pki_security_domain_name}"
+subca_key_size=256
+subca_key_curvename=nistp256
+subca_key_type=ecc
+subca_signing_algorithm=SHA256withEC
+subca_signing_signingalgorithm=SHA256withEC
+subca_ocsp_signing_signingalgorithm=SHA256withEC
+subca_save_p12=false
+subca_sign_cert_subject_name="cn=Certificate\ Authority\ 2,ou=${subca_instance_name},o=${pki_security_domain_name}"
+subca_subsystem_cert_subject_name="cn=CA\ Subsystem\ Certificate\ 2,ou=${subca_instance_name},o=${pki_security_domain_name}"
+subca_ocsp_cert_subject_name="cn=OCSP\ Signing\ Certificate\ 2,ou=${subca_instance_name},o=${pki_security_domain_name}"
+subca_server_cert_subject_name="cn=${pki_host},ou=${subca_instance_name},o=${pki_security_domain_name}"
+subca_audit_signing_cert_subject_name="cn=CA\ Audit\ Signing\ Certificate\ 2,ou=${subca_instance_name},o=${pki_security_domain_name}"
 
+
+
+##############################################################################
+##  C A L C U L A T E   P K I   I N S T A N C E   P I N S                   ##
+##############################################################################
+
+##  PKI Subsystem Instance PINS
+##subca_preop_pin=`cat /var/lib/${subca_instance_name}/conf/CS.cfg \
+##	| grep preop.pin | grep -v grep | awk -F= '{print $2}'`
+## should get the following from the system root user who created the instance:
+subca_preop_pin=
 
 
 ##############################################################################
@@ -316,8 +358,20 @@ subca_audit_signing_cert_subject_name="cn=CA\ Audit\ Signing\ Certificate\ 2,o=$
 usage_errors=0
 usage_error_preamble="ERROR:  User MUST define a value for"
 
+if [ "${subca_preop_pin}" = "" ] ; then
+	printf "${usage_error_preamble} 'subca_preop_pin'!\n"
+	usage_errors=`expr ${usage_errors} + 1`
+fi
+if [ "${pki_silent_security_database_repository}" = "" ] ; then
+	printf "${usage_error_preamble} 'pki_silent_security_database_repository'!\n"
+	usage_errors=`expr ${usage_errors} + 1`
+fi
 if [ "${pki_silent_security_database_password}" = "" ] ; then
 	printf "${usage_error_preamble} 'pki_silent_security_database_password'!\n"
+	usage_errors=`expr ${usage_errors} + 1`
+fi
+if [ "${pki_silent_security_token_name}" = "" ] ; then
+	printf "${usage_error_preamble} 'pki_silent_security_token_name'!\n"
 	usage_errors=`expr ${usage_errors} + 1`
 fi
 if [ "${pki_security_domain_name}" = "" ] ; then
@@ -332,12 +386,12 @@ if [ "${pki_bind_password}" = "" ] ; then
 	printf "${usage_error_preamble} 'pki_bind_password'!\n"
 	usage_errors=`expr ${usage_errors} + 1`
 fi
-if [ "${subca_token_password}" = "" ] ; then
-	printf "${usage_error_preamble} 'subca_token_password'!\n"
+if [ "${subca_token_name}" = "" ] ; then
+	printf "${usage_error_preamble} 'subca_token_name'!\n"
 	usage_errors=`expr ${usage_errors} + 1`
 fi
-if [ "${subca_backup_password}" = "" ] ; then
-	printf "${usage_error_preamble} 'subca_backup_password'!\n"
+if [ "${subca_token_password}" = "" ] ; then
+	printf "${usage_error_preamble} 'subca_token_password'!\n"
 	usage_errors=`expr ${usage_errors} + 1`
 fi
 if [ "${pki_email_name}" = "" ] ; then
@@ -366,17 +420,17 @@ configuration_errors=0
 configuration_error_preamble="ERROR:  A PKI Instance named"
 configuration_error_postamble="EXISTS,\n        but has PREVIOUSLY been CONFIGURED!"
 
-if [ ! -f "/var/lib/${subca_instance_name}/conf/CS.cfg" ] ; then
-	printf "${existence_error_preamble} '${subca_instance_name}' EXISTS!\n"
-	existence_errors=`expr ${existence_errors} + 1`
-else
-	subca_configuration_check=`grep -c preop /var/lib/${subca_instance_name}/conf/CS.cfg`
-	if [ ${subca_configuration_check} -eq 0 ] ; then
-	    printf "${configuration_error_preamble} '${subca_instance_name}' "
-		printf "${configuration_error_postamble}\n"
-		configuration_errors=`expr ${configuration_errors} + 1`
-	fi
-fi
+##if [ ! -f "/var/lib/${subca_instance_name}/conf/CS.cfg" ] ; then
+##	printf "${existence_error_preamble} '${subca_instance_name}' EXISTS!\n"
+##	existence_errors=`expr ${existence_errors} + 1`
+##else
+##	subca_configuration_check=`grep -c preop /var/lib/${subca_instance_name}/conf/CS.cfg`
+##	if [ ${subca_configuration_check} -eq 0 ] ; then
+##	    printf "${configuration_error_preamble} '${subca_instance_name}' "
+##		printf "${configuration_error_postamble}\n"
+##		configuration_errors=`expr ${configuration_errors} + 1`
+##	fi
+##fi
 
 
 if	[ ${usage_errors} -ne 0 ]     ||
@@ -399,19 +453,18 @@ fi
 
 
 ## (4) Check for old PKI Silent Security Databases, but DO NOT remove them!
-##     Instead, inform the user and exit this script.
+##     Instead, inform the user and continue with this script.
 if	[ -f "${pki_silent_security_database_repository}/cert8.db" ] ||
 	[ -f "${pki_silent_security_database_repository}/key3.db" ] ||
 	[ -f "${pki_silent_security_database_repository}/secmod.db" ] ; then
 	printf "\n"
 	printf "WARNING:  At least one of the security databases\n"
 	printf "          (i. e. - 'cert8.db', 'key3.db', and/or 'secmod.db')\n"
-	printf "          required by '${subca_silent_script}' exists at the\n"
+	printf "          required by '${subca_silentEC_script}' exists at the\n"
 	printf "          specified location '${pki_silent_security_database_repository}'.\n"
 	printf "\n"
-	printf "          Please MANUALLY move or erase these security database(s),\n"
-	printf "          or specify a different location before re-running this script.\n\n"
-	exit 255
+	printf "          Continue...\n\n"
+#	exit 255
 fi
 
 
@@ -426,22 +479,13 @@ printf "Done.\n\n"
 
 
 
-##############################################################################
-##  C A L C U L A T E   P K I   I N S T A N C E   P I N S                   ##
-##############################################################################
-
-##  PKI Subsystem Instance PINS
-subca_preop_pin=`cat /var/lib/${subca_instance_name}/conf/CS.cfg \
-	| grep preop.pin | grep -v grep | awk -F= '{print $2}'`
-
-
 
 ##############################################################################
 ##  C E R T I F I C A T E   A U T H O R I T Y                               ##
 ##############################################################################
 ##
 ##  For example, upon completion,
-##  execute '/sbin/service ${subca_init_script} status ${subca_instance_name}':
+##  execute '/sbin/service ${subca_instance_name} status':
 ##
 ##      ${subca_instance_name} (pid 7843) is running ...
 ##
@@ -459,8 +503,9 @@ subca_preop_pin=`cat /var/lib/${subca_instance_name}/conf/CS.cfg \
 ##          ==================================================================
 ##
 
-##  Configure Subordinate CA
-printf "'${subca_silent_script}':  Configuring '${subca_instance_name}' . . .\n"
+export NSS_USE_DECODED_CKA_EC_POINT=1
+##  Configure Subordinate ECC CA
+printf "'${subca_silentEC_script}':  Configuring '${subca_instance_name}' . . .\n"
 pkisilent ConfigureSubCA \
 	-cs_hostname "${pki_host}" \
 	-cs_port ${subca_admin_port} \
@@ -474,8 +519,8 @@ pkisilent ConfigureSubCA \
 	-ca_port ${ca_nonssl_port} \
 	-ca_ssl_port ${ca_ee_port} \
 	-client_certdb_dir ${pki_silent_security_database_repository} \
-	-client_certdb_pwd ${pki_silent_security_database_password} \
 	-client_token_name ${pki_silent_security_token_name} \
+	-client_certdb_pwd ${pki_silent_security_database_password} \
 	-preop_pin ${subca_preop_pin} \
 	-domain_name "${pki_security_domain_name}" \
 	-admin_user ${pki_silent_admin_user} \
@@ -490,16 +535,31 @@ pkisilent ConfigureSubCA \
 	-db_name "${subca_db_name}" \
 	-key_size ${subca_key_size} \
 	-key_type ${subca_key_type} \
-        -signing_algorithm ${subca_signing_algorithm} \
-        -signing_signingalgorithm ${subca_signing_signingalgorithm} \
-        -ocsp_signing_signingalgorithm ${subca_ocsp_signing_signingalgorithm} \
+	-key_curvename ${subca_key_curvename} \
+	-signing_algorithm ${subca_signing_algorithm} \
+	-signing_key_type ${subca_key_type} \
+	-signing_key_curvename ${subca_key_curvename} \
+	-ocsp_signing_key_size ${subca_key_size} \
+	-ocsp_signing_key_type ${subca_key_type} \
+	-ocsp_signing_key_curvename ${subca_key_curvename} \
+	-subsystem_key_size ${subca_key_size} \
+	-subsystem_key_type ${subca_key_type} \
+	-subsystem_key_curvename ${subca_key_curvename} \
+	-audit_signing_key_size 2048 \
+	-audit_signing_key_type rsa \
+	-sslserver_key_size ${subca_key_size} \
+	-sslserver_key_type ${subca_key_type} \
+	-sslserver_key_curvename ${subca_key_curvename} \
+	-signing_signingalgorithm ${subca_signing_signingalgorithm} \
+	-ocsp_signing_signingalgorithm ${subca_ocsp_signing_signingalgorithm} \
 	-token_name ${subca_token_name} \
 	-token_pwd ${subca_token_password} \
 	-agent_key_size ${subca_agent_key_size} \
 	-agent_key_type ${subca_agent_key_type} \
 	-agent_cert_subject "${subca_agent_cert_subject}" \
+	-save_p12 ${subca_save_p12} \
 	-backup_pwd ${subca_backup_password} \
-	-subsystem_name "${ca_subsystem_name}" \
+	-subsystem_name "${subca_subsystem_name}" \
 	-subca_sign_cert_subject_name "${subca_sign_cert_subject_name}" \
 	-subca_subsystem_cert_subject_name "${subca_subsystem_cert_subject_name}" \
 	-subca_ocsp_cert_subject_name "${subca_ocsp_cert_subject_name}" \
@@ -509,7 +569,9 @@ pkisilent ConfigureSubCA \
 	| tee ${pki_silent_subca_log}
 
 ##  Restart Subordinate CA
-/sbin/service ${subca_init_script} restart ${subca_instance_name}
+## Do this manually as root
+	printf "If configured without errors, ask the OS root user to restart the CS instance:\n"
+	printf "/sbin/service '${subca_instance_name}' restart\n\n"
 
 exit 0
 
