Build changes required to integrate Dogtag into Fedora.
git-svn-id: svn+ssh://svn.fedorahosted.org/svn/pki/trunk@805 c9f7a03b-bd48-0410-a16d-cbbf54688b0b

diff --git a/pki/dogtag/common-ui/build_dogtag b/pki/dogtag/common-ui/build_dogtag
--- a/pki/dogtag/common-ui/build_dogtag
+++ b/pki/dogtag/common-ui/build_dogtag
@@ -33,6 +33,50 @@ export DOGTAG_COMPONENT
 DOGTAG_SPECFILE="dogtag-pki-common-ui.spec"
 export DOGTAG_SPECFILE
 
+# Set PKI 'ant' environment variables (originally obtained from specfile)
+PKI_PRODUCT_UI_FLAVOR_PREFIX="dogtag"
+export PKI_PRODUCT_UI_FLAVOR_PREFIX
+PKI_PRODUCT_PREFIX="pki"
+export PKI_PRODUCT_PREFIX
+PKI_PRODUCT="common-ui"
+export PKI_PRODUCT
+PKI_VERSION="1.3.0"
+export PKI_VERSION
+
+# Set Dogtag helper variables
+DOGTAG_COMPONENT_NAME=${PKI_PRODUCT}
+export DOGTAG_COMPONENT_NAME
+DOGTAG_WGET_URL=http://cvs.fedora.redhat.com/viewvc
+export DOGTAG_WGET_URL
+
+# Obtain '${DOGTAG_SPECFILE}' as necessary
+if [ "$1" = "refresh" ]; then
+	if [ -f "${DOGTAG_SPECFILE}" ]; then
+		printf "Removing '${DOGTAG_SPECFILE}' . . . "
+		rm -rf ${DOGTAG_SPECFILE}
+		printf "done.\n"
+	fi
+	shift
+fi
+if [ ! -f "${DOGTAG_SPECFILE}" ]; then
+	# Check for Fedora Operating System
+	if [ ! -f /etc/fedora-release ]; then
+		printf "'${DOGTAG_COMPONENT_NAME}' ONLY builds on Fedora!\n"
+		exit 255
+	fi
+	# Obtain Fedora Operating System Version
+	FEDORA_VERSION="F-`cat /etc/fedora-release | awk '{print $3}'`"
+	export FEDORA_VERSION
+	# Retrieve '${DOGTAG_SPECFILE}' from Koji
+	printf "Fetching '${DOGTAG_SPECFILE}' for '${FEDORA_VERSION}' . . .\n"
+	wget -O ${DOGTAG_SPECFILE} ${DOGTAG_WGET_URL}/${FEDORA_VERSION}/${DOGTAG_COMPONENT_NAME}/${DOGTAG_SPECFILE}?view=co
+	if [ ! -s "${DOGTAG_SPECFILE}" ]; then
+		printf "Failed to fetch '${DOGTAG_SPECFILE}' for '${FEDORA_VERSION}'!\n"
+		rm -rf ${DOGTAG_SPECFILE}
+		exit 255
+	fi
+fi
+
 # Invoke the shared Dogtag PKI build script
 config-ext/build_dogtag_pki $@
 
