Bugzilla Bug #488338 -  start/stop scripts should list all the available port numbers with their functionality Bugzilla Bug #440164 -  Dogtag subsystems should show up in Fedora8 administrator Services window
git-svn-id: svn+ssh://svn.fedorahosted.org/svn/pki/trunk@297 c9f7a03b-bd48-0410-a16d-cbbf54688b0b

diff --git a/pki/base/kra/shared/etc/init.d/httpd b/pki/base/kra/shared/etc/init.d/httpd
--- a/pki/base/kra/shared/etc/init.d/httpd
+++ b/pki/base/kra/shared/etc/init.d/httpd
@@ -21,8 +21,8 @@
 # [PKI_INSTANCE_ID]    Startup script for Tomcat 5.0, the Apache Servlet Engine
 #
 # chkconfig:    - 82 18
-# description:  Tomcat 5.0 is the Apache Servlet Engine RI
-#               for Servlet 2.4/JSP 2.0
+# description:  Data Recovery Manager \
+#               (Tomcat 5.0)
 # processname:  [PKI_INSTANCE_ID]
 # pidfile:      /var/run/[PKI_INSTANCE_ID].pid
 # config:       /etc/[PKI_INSTANCE_ID]/tomcat5.conf
@@ -115,7 +115,7 @@ else
 	# The checkpid() function is provided for platforms that do not
 	# contain the "/etc/init.d/functions" file (e. g. - Solaris) . . .
 
-	# Check if $pid (could be plural) are running (keep count)
+	# Check if ${pid} (could be plural) are running (keep count)
 	checkpid()
 	{
 		rv=0
@@ -206,7 +206,90 @@ fi
 # Please use the /etc/tomcat.conf file instead ; it will
 # be read by the $tomcat script
 
+pidfile=${PIDFILE:-/var/run/[PKI_INSTANCE_ID].pid}
+lockfile=${LOCKFILE:-/var/lock/subsys/[PKI_INSTANCE_ID]}
+RESTART_SERVER=/var/lib/[PKI_INSTANCE_ID]/conf/restart_server_after_configuration
 RETVAL=0
+
+check_pki_configuration_status()
+{
+	rv=0
+
+	rv=`grep -c ^preop /etc/[PKI_INSTANCE_ID]/CS.cfg`
+
+	rv=`expr ${rv} + 0`
+
+	if [ ${rv} -ne 0 ] ; then
+		echo "    '[PKI_INSTANCE_ID]' must still be CONFIGURED!"
+		echo "    (see /var/log/[PKI_INSTANCE_ID]-install.log)"
+	elif [ -f ${RESTART_SERVER} ] ; then
+		echo "    Although '[PKI_INSTANCE_ID]' has been CONFIGURED, it must still be RESTARTED!"
+		rv=255
+	fi
+
+	return ${rv}
+}
+
+get_pki_status_definitions()
+{
+	# establish well-known strings
+	begin_pki_status_comment="<!-- DO NOT REMOVE - Begin PKI Status Definitions -->"
+	end_pki_status_comment="<!-- DO NOT REMOVE - End PKI Status Definitions -->"
+	total_ports=0
+	unsecure_port_statement="Unsecure Port     = "
+	secure_agent_port_statement="Secure Agent Port = "
+	secure_ee_port_statement="Secure EE Port    = "
+	secure_admin_port_statement="Secure Admin Port = "
+	tomcat_port_statement="Tomcat Port       = "
+
+	# initialize looping variables
+	pki_status_comment_found=0
+
+	# first check to see that an instance-specific "server.xml" file exists
+	if [ ! -f [PKI_SERVER_XML_CONF] ] ; then
+		echo "File '[PKI_SERVER_XML_CONF]' does not exist!"
+		exit 255
+	fi
+
+	# read this instance-specific "server.xml" file line-by-line
+	# to obtain the current PKI Status Definitions
+	exec < [PKI_SERVER_XML_CONF]
+	while read line; do
+		# first look for the well-known end PKI Status comment
+		# (to turn off processing)
+		if [ "$line" == "$end_pki_status_comment" ] ; then
+			pki_status_comment_found=0
+			break;
+		fi
+
+		# then look for the well-known begin PKI Status comment
+		# (to turn on processing)
+		if [ "$line" == "$begin_pki_status_comment" ] ; then
+			pki_status_comment_found=1
+		fi
+
+		# once the well-known begin PKI Status comment has been found,
+		# begin processing to obtain all of the PKI Status Definitions
+		if [ $pki_status_comment_found -eq 1 ] ; then
+			# look for a PKI Status Definition and print it
+			head=`echo "$line" | cut -b1-20`
+			if	[ "$head" == "$unsecure_port_statement"     ] ||
+				[ "$head" == "$secure_agent_port_statement" ] ||
+				[ "$head" == "$secure_ee_port_statement"    ] ||
+				[ "$head" == "$secure_admin_port_statement" ] ||
+				[ "$head" == "$tomcat_port_statement"       ] ; then
+				echo "    $line"
+				total_ports=`expr ${total_ports} + 1`
+			fi
+		fi
+    done
+
+	if [ ${total_ports} -eq 6 ] ; then
+		return 0
+	else
+		return 255
+	fi
+}
 
 get_pki_secure_port()
 {
@@ -259,14 +342,17 @@ get_pki_secure_port()
 	return 255
 }
 
-# See how we were called.
 start()
 {
 	echo -n "Starting $TOMCAT_PROG: "
 
-	if [ -f /var/lock/subsys/[PKI_INSTANCE_ID] ] ; then
-		if [ -f /var/run/[PKI_INSTANCE_ID].pid ]; then
-			read kpid < /var/run/[PKI_INSTANCE_ID].pid
+	if [ -f ${RESTART_SERVER} ] ; then
+		rm -f ${RESTART_SERVER}
+	fi
+
+	if [ -f ${lockfile} ] ; then
+		if [ -f ${pidfile} ]; then
+			read kpid < ${pidfile}
 			if checkpid $kpid 2>&1; then
 				echo
 				echo "process already running"
@@ -281,7 +367,7 @@ start()
 		fi
 	fi
 
-	CATALINA_PID=/var/run/[PKI_INSTANCE_ID].pid
+	CATALINA_PID=${pidfile}
 	export CATALINA_PID
 	touch $CATALINA_PID
 	chown $TOMCAT_USER:$TOMCAT_GROUP $CATALINA_PID
@@ -779,13 +865,13 @@ start()
 	fi
 
 	RETVAL=$?
-	[ $RETVAL = 0 ] && touch /var/lock/subsys/[PKI_INSTANCE_ID]
+	[ $RETVAL = 0 ] && touch ${lockfile}
 
 	if [ $RETVAL = 0 ] ; then
 		count=0;
 
 		let swait=$STARTUP_WAIT
-		while	[ ! -s /var/run/[PKI_INSTANCE_ID].pid ] &&
+		while	[ ! -s ${pidfile} ] &&
 				[ $count -lt $swait ]
 		do
 			echo -n "."
@@ -833,8 +919,8 @@ stop()
 {
 	echo -n "Stopping $TOMCAT_PROG: "
 
-	if [ -f /var/lock/subsys/[PKI_INSTANCE_ID] ] ; then
-		CATALINA_PID=/var/run/[PKI_INSTANCE_ID].pid
+	if [ -f ${lockfile} ] ; then
+		CATALINA_PID=${pidfile}
 		export CATALINA_PID
 
 		# daemon --user $TOMCAT_USER $TOMCAT_SCRIPT stop
@@ -849,8 +935,8 @@ stop()
 		if [ $RETVAL = 0 ]; then
 			count=0;
 
-			if [ -f /var/run/[PKI_INSTANCE_ID].pid ]; then
-				read kpid < /var/run/[PKI_INSTANCE_ID].pid
+			if [ -f ${pidfile} ]; then
+				read kpid < ${pidfile}
 				let kwait=$SHUTDOWN_WAIT
 
 				until	[ `ps -p $kpid | grep -c $kpid` = '0' ] ||
@@ -866,8 +952,8 @@ stop()
 				fi
 			fi
 
-			rm -f /var/lock/subsys/[PKI_INSTANCE_ID]
-			rm -f /var/run/[PKI_INSTANCE_ID].pid
+			rm -f ${lockfile}
+			rm -f ${pidfile}
 
 			if [ -x /etc/init.d/functions ]; then
 				if [ "$CONSOLETYPE" = "serial" ]; then
@@ -895,6 +981,31 @@ stop()
 	fi
 }
 
+status()
+{
+	if [ -f ${pidfile} ] ; then
+		pid=`cat ${pidfile}`
+		if [ "${pid}" == "" ] ; then
+			echo "[PKI_INSTANCE_ID] pid file exists but is empty"
+		elif kill -0 ${pid} > /dev/null 2>&1 ; then
+			echo "[PKI_INSTANCE_ID] (pid ${pid}) is running ..."
+			echo
+			check_pki_configuration_status
+			if [ $? -eq 0 ] ; then
+				get_pki_status_definitions
+				if [ $? -ne 0 ] ; then
+					echo "[PKI_INSTANCE_ID] Status Definitions not found"
+				fi
+			fi
+			echo
+		else
+			echo "[PKI_INSTANCE_ID] is dead but pid file exists"
+		fi
+	else
+		echo "[PKI_INSTANCE_ID] is stopped"
+	fi
+}
+
 # See how we were called.
 case "$1" in
 	start)
@@ -909,18 +1020,21 @@ case "$1" in
 		start
 		;;
 	condrestart)
-		if [ -f /var/run/[PKI_INSTANCE_ID].pid ] ; then
+		if [ -f ${pidfile} ] ; then
 			stop
 			sleep 2	
 			start
 		else
 			echo -n "Unable to restart process since "
-			echo -n "'/var/run/[PKI_INSTANCE_ID].pid' does not exist!"
+			echo -n "'${pidfile}' does not exist!"
 			echo
 		fi
 		;;
+	status)
+		status
+		;;
 	*)
-		echo "Usage: $TOMCAT_PROG {start|stop|restart|condrestart}"
+		echo "Usage: $TOMCAT_PROG {start|stop|restart|condrestart|status}"
 		exit 1
 esac
 
diff --git a/pki/base/ra/etc/init.d/httpd b/pki/base/ra/etc/init.d/httpd
--- a/pki/base/ra/etc/init.d/httpd
+++ b/pki/base/ra/etc/init.d/httpd
@@ -21,8 +21,8 @@
 # [INSTANCE_ID]    Startup script for the Apache HTTP Server
 #
 # chkconfig:    - 86 14
-# description:  Apache is a World Wide Web server.  It is used to serve \
-#               HTML files and CGI.
+# description:  Registration Authority \
+#               (Apache 2.2)
 # processname:  [INSTANCE_ID]
 # config:       [HTTPD_CONF]
 # pidfile:      [SERVER_ROOT]/logs/[INSTANCE_ID].pid
@@ -95,7 +95,7 @@ else
 	# The checkpid() function is provided for platforms that do not
 	# contain the "/etc/init.d/functions" file (e. g. - Solaris) . . .
 
-	# Check if $pid (could be plural) are running (keep count)
+	# Check if ${pid} (could be plural) are running (keep count)
 	checkpid()
 	{
 		rv=0
@@ -160,6 +160,7 @@ httpd=${HTTPD:-[FORTITUDE_DIR]/sbin/httpd}
 prog=[INSTANCE_ID]
 pidfile=${PIDFILE:-[SERVER_ROOT]/logs/[INSTANCE_ID].pid}
 lockfile=${LOCKFILE:-/var/lock/subsys/[INSTANCE_ID]}
+RESTART_SERVER=/var/lib/[INSTANCE_ID]/conf/restart_server_after_configuration
 RETVAL=0
 
 # see if httpd is linked with the openldap libraries - we need to override them
@@ -170,11 +171,7 @@ if [ ${OS} = "Linux" ]; then
 
 	if [ $hasopenldap -eq 1 ] ; then
 		LD_PRELOAD="[SYSTEM_USER_LIBRARIES]/libldap60.so"
-		if [ -e [SYSTEM_USER_LIBRARIES]/dirsec/libssl3.so ] ; then
-			LD_PRELOAD="[SYSTEM_USER_LIBRARIES]/dirsec/libssl3.so:${LD_PRELOAD}"
-		else
-			LD_PRELOAD="[SYSTEM_USER_LIBRARIES]/libssl3.so:${LD_PRELOAD}"
-                fi
+		LD_PRELOAD="[SYSTEM_USER_LIBRARIES]/libssl3.so:${LD_PRELOAD}"
 		export LD_PRELOAD
 	fi
 elif [ ${OS} = "SunOS" ] ; then
@@ -182,6 +179,100 @@ elif [ ${OS} = "SunOS" ] ; then
 	LD_PRELOAD_64="[SYSTEM_USER_LIBRARIES]/dirsec/libssl3.so:${LD_PRELOAD_64}"
 	export LD_PRELOAD_64
 fi
+
+check_pki_configuration_status()
+{
+	rv=0
+
+	rv=`grep -c ^preop /etc/[INSTANCE_ID]/CS.cfg`
+
+	rv=`expr ${rv} + 0`
+
+	if [ ${rv} -ne 0 ] ; then
+		echo "    '[INSTANCE_ID]' must still be CONFIGURED!"
+		echo "    (see /var/log/[INSTANCE_ID]-install.log)"
+	elif [ -f ${RESTART_SERVER} ] ; then
+		echo "    Although '[INSTANCE_ID]' has been CONFIGURED, it must still be RESTARTED!"
+		rv=255
+	fi
+
+	return ${rv}
+}
+
+get_pki_status_definitions()
+{
+	# establish well-known strings
+	listen_statement="Listen"
+	total_ports=0
+	UNSECURE_PORT=""
+	CLIENTAUTH_PORT=""
+	NON_CLIENTAUTH_PORT=""
+
+	# check to see that an instance-specific "httpd.conf" file exists
+	if [ ! -f [HTTPD_CONF] ] ; then
+		echo "File '[HTTPD_CONF]' does not exist!"
+		exit 255
+	fi
+
+	# check to see that an instance-specific "nss.conf" file exists
+	if [ ! -f [NSS_CONF] ] ; then
+		echo "File '[NSS_CONF]' does not exist!"
+		exit 255
+	fi
+
+	# read this instance-specific "httpd.conf" file line-by-line
+	# to obtain the current value of the PKI unsecure port
+
+	exec < [HTTPD_CONF]
+	while read line; do
+		# look for the listen statement
+		head=`echo $line | cut -b1-6`
+		if [ "$head" == "$listen_statement" ] ; then
+			# once the 'unsecure' listen statement has been found,
+			# extract the numeric port information
+			port=`echo $line | cut -d: -f2`
+			UNSECURE_PORT=$port
+			echo "    Unsecure Port              = http://[SERVER_NAME]:${UNSECURE_PORT}"
+			total_ports=`expr ${total_ports} + 1`
+			break;
+		fi
+	done
+
+	# read this instance-specific "nss.conf" file line-by-line
+	# to obtain the current value of the "clientauth" PKI secure port
+	# AND the current value of the "non-clientauth" PKI secure port
+
+	exec < [NSS_CONF]
+	while read line; do
+		# look for the listen statement
+		head=`echo $line | cut -b1-6`
+		if	[ "$head" == "$listen_statement" ] &&
+			[ ${total_ports} -eq 2           ] ; then
+			# once the 'non-clientauth' listen statement has been found,
+			# extract the numeric port information
+			non_clientauth_port=`echo $line | cut -d: -f2`
+			NON_CLIENTAUTH_PORT=$non_clientauth_port
+			echo "    Secure Non-Clientauth Port = https://[SERVER_NAME]:${NON_CLIENTAUTH_PORT}"
+			total_ports=`expr ${total_ports} + 1`
+			break
+		fi
+		if	[ "$head" == "$listen_statement" ] &&
+			[ ${total_ports} -eq 1           ] ; then
+			# once the 'clientauth' listen statement has been found,
+			# extract the numeric port information
+			clientauth_port=`echo $line | cut -d: -f2`
+			CLIENTAUTH_PORT=$clientauth_port
+			echo "    Secure Clientauth Port     = https://[SERVER_NAME]:${CLIENTAUTH_PORT}"
+			total_ports=`expr ${total_ports} + 1`
+		fi
+	done
+
+	if [ ${total_ports} -eq 3 ] ; then
+		return 0
+	else
+		return 255
+	fi
+}
 
 get_pki_secure_port()
 {
@@ -195,13 +286,14 @@ get_pki_secure_port()
 	fi
 
 	# read this instance-specific "nss.conf" file line-by-line
-	# to obtain the current value of the PKI secure port
+	# to obtain the current value of the "clientauth" PKI secure port
+	
 	exec < [NSS_CONF]
 	while read line; do
 		# look for the listen statement
 		head=`echo $line | cut -b1-6`
 		if [ "$head" == "$listen_statement" ] ; then
-			# once the listen statement has been found,
+			# once the 'clientauth' listen statement has been found,
 			# extract the numeric port information
 			port=`echo $line | cut -d: -f2`
 			SECURE_PORT=$port
@@ -216,8 +308,13 @@ get_pki_secure_port()
 # things -- attempting to start while running is a failure, and shutdown
 # when not running is also a failure.  So we just do it the way init scripts
 # are expected to behave here.
-start() {
+start()
+{
 	echo -n $"Starting $prog: "
+
+	if [ -f ${RESTART_SERVER} ] ; then
+		rm -f ${RESTART_SERVER}
+	fi
 
 	if [ -f ${lockfile} ] ; then
 		if [ -f ${pidfile} ]; then
@@ -314,7 +411,8 @@ start() {
 	return $RETVAL
 }
 
-stop() {
+stop()
+{
 	echo -n "Stopping $prog: "
 
 	if [ -f ${lockfile} ] ; then
@@ -364,7 +462,8 @@ stop() {
 	fi
 }
 
-reload() {
+reload()
+{
 	echo -n $"Reloading $prog: "
 
 	if ! LANG=$HTTPD_LANG $httpd $OPTIONS -t >&/dev/null; then
@@ -400,6 +499,31 @@ reload() {
 	echo
 }
 
+status()
+{
+	if [ -f ${pidfile} ] ; then
+		pid=`cat ${pidfile}`
+		if [ "${pid}" == "" ] ; then
+			echo "[INSTANCE_ID] pid file exists but is empty"
+		elif kill -0 ${pid} > /dev/null 2>&1 ; then
+			echo "[INSTANCE_ID] (pid ${pid}) is running ..."
+			echo
+			check_pki_configuration_status
+			if [ $? -eq 0 ] ; then
+				get_pki_status_definitions
+				if [ $? -ne 0 ] ; then
+					echo "[INSTANCE_ID] Status Definitions not found"
+				fi
+			fi
+			echo
+		else
+			echo "[INSTANCE_ID] is dead but pid file exists"
+		fi
+	else
+		echo "[INSTANCE_ID] is stopped"
+	fi
+}
+
 # See how we were called.
 case "$1" in
 	start)
@@ -407,10 +531,6 @@ case "$1" in
 		;;
 	stop)
 		stop
-		;;
-	status)
-		status $httpd
-		RETVAL=$?
 		;;
 	restart)
 		stop
@@ -431,8 +551,11 @@ case "$1" in
 	reload)
 		reload
 		;;
+	status)
+		status
+		;;
 	*)
-		echo $"Usage: $prog {start|stop|restart|condrestart|reload|status|fullstatus|graceful|help|configtest}"
+		echo $"Usage: $prog {start|stop|restart|condrestart|reload|status}"
 		exit 1
 esac
 
