Bugzilla Bug #669226 - Remove Legacy Build System (Ant + Autoconf --> CMake)
git-svn-id: svn+ssh://svn.fedorahosted.org/svn/pki/trunk@2057 c9f7a03b-bd48-0410-a16d-cbbf54688b0b

diff --git a/pki/base/java-tools/templates/pretty_print_cert_command_wrapper.in b/pki/base/java-tools/templates/pretty_print_cert_command_wrapper.in
--- a/pki/base/java-tools/templates/pretty_print_cert_command_wrapper.in
+++ b/pki/base/java-tools/templates/pretty_print_cert_command_wrapper.in
@@ -1,21 +1,23 @@
 #!/bin/sh
+#
 # --- BEGIN COPYRIGHT BLOCK ---
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation; version 2 of the License.
-# 
+#
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
-# 
+#
 # You should have received a copy of the GNU General Public License along
 # with this program; if not, write to the Free Software Foundation, Inc.,
 # 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
-# 
+#
 # Copyright (C) 2007 Red Hat, Inc.
 # All rights reserved.
 # --- END COPYRIGHT BLOCK ---
+#
 
 # Check to insure that this script's original invocation directory
 # has not been deleted!
@@ -24,19 +26,24 @@ if [ $? -ne 0 ] ; then
     echo "Cannot invoke '$0' from non-existent directory!"
     exit 255
 fi
- 
+
 
 ###############################################################################
 ##  (1) Specify variables used by this script.                               ##
 ###############################################################################
 
-PRODUCT=[PKI_PRODUCT]
-SUBSYSTEM=[PKI_SUBSYSTEM]
-COMMAND=[PKI_COMMAND]
+PRODUCT=@PKI_PRODUCT@
+COMMAND=@PKI_COMMAND@
 
 
 ###############################################################################
-##  (2) Define helper functions.                                             ##
+##  (2) Check for valid usage of this command wrapper.                       ##
+###############################################################################
+
+
+
+###############################################################################
+##  (3) Define helper functions.                                             ##
 ###############################################################################
 
 invalid_operating_system() {
@@ -53,50 +60,30 @@ invalid_architecture() {
 
 
 ###############################################################################
-##  (3) Set environment variables.                                           ##
-##                                                                           ##
-##      Set the LD_LIBRARY_PATH environment variable to determine the        ##
+##  (4) Set the LD_LIBRARY_PATH environment variable to determine the        ##
 ##      search order this command wrapper uses to find shared libraries.     ##
-##                                                                           ##
-##      Set the PATH environment variable to determine the search            ##
-##      order this command wrapper uses to find binary executables.          ##
-##                                                                           ##
-##      NOTE:  Since "/bin" is nothing more than a symbolic link to          ##
-##             "/usr/bin" on Solaris, this directory will always be          ##
-##             excluded from the search path on this platform.               ##
-##                                                                           ##
 ###############################################################################
 
 OS=`uname -s`
 
 if [ "${OS}" = "Linux" ] ; then
     ARCHITECTURE=`uname -i`
+    JAVA="java"
+    JAVA_OPTIONS=""
+
     if [ "${ARCHITECTURE}" = "i386" ] ; then
         LD_LIBRARY_PATH=/usr/lib:/lib
-        LD_LIBRARY_PATH=/usr/lib/dirsec:${LD_LIBRARY_PATH}
-        LD_LIBRARY_PATH=/usr/lib/${PRODUCT}:${LD_LIBRARY_PATH}
-        LD_LIBRARY_PATH=/usr/lib/${PRODUCT}/${SUBSYSTEM}:${LD_LIBRARY_PATH}
+        LD_LIBRARY_PATH=/usr/lib/jss:${LD_LIBRARY_PATH}
+        LD_LIBRARY_PATH=/usr/lib/osutil:${LD_LIBRARY_PATH}
         export LD_LIBRARY_PATH
-
-        PATH=/usr/lib/${PRODUCT}:/usr/bin:/bin
-        PATH=/usr/lib/${PRODUCT}/${SUBSYSTEM}:${PATH}
-        export PATH
     elif [ "${ARCHITECTURE}" = "x86_64" ] ; then
         LD_LIBRARY_PATH=/usr/lib:/lib
-        LD_LIBRARY_PATH=/usr/lib/dirsec:${LD_LIBRARY_PATH}
-        LD_LIBRARY_PATH=/usr/lib/${PRODUCT}:${LD_LIBRARY_PATH}
-        LD_LIBRARY_PATH=/usr/lib/${PRODUCT}/${SUBSYSTEM}:${LD_LIBRARY_PATH}
+        LD_LIBRARY_PATH=/usr/lib/jss:${LD_LIBRARY_PATH}
+        LD_LIBRARY_PATH=/usr/lib/osutil:${LD_LIBRARY_PATH}
         LD_LIBRARY_PATH=/usr/lib64:/lib64:${LD_LIBRARY_PATH}
-        LD_LIBRARY_PATH=/usr/lib64/dirsec:${LD_LIBRARY_PATH}
-        LD_LIBRARY_PATH=/usr/lib64/${PRODUCT}:${LD_LIBRARY_PATH}
-        LD_LIBRARY_PATH=/usr/lib64/${PRODUCT}/${SUBSYSTEM}:${LD_LIBRARY_PATH}
+        LD_LIBRARY_PATH=/usr/lib64/jss:${LD_LIBRARY_PATH}
+        LD_LIBRARY_PATH=/usr/lib64/osutil:${LD_LIBRARY_PATH}
         export LD_LIBRARY_PATH
-
-        PATH=/usr/lib/${PRODUCT}:/usr/bin:/bin
-        PATH=/usr/lib/${PRODUCT}/${SUBSYSTEM}:${PATH}
-        PATH=/usr/lib64/${PRODUCT}:${PATH}
-        PATH=/usr/lib64/${PRODUCT}/${SUBSYSTEM}:${PATH}
-        export PATH
     else
         invalid_architecture "${ARCHITECTURE}"
         exit 255
@@ -108,33 +95,24 @@ elif [ "${OS}" = "SunOS" ] ; then
         ARCHITECTURE="sparcv9"
     fi
     if [ "${ARCHITECTURE}" = "sparc" ] ; then
-        LD_LIBRARY_PATH=/usr/lib:/lib
-        LD_LIBRARY_PATH=/usr/lib/dirsec:${LD_LIBRARY_PATH}
-        LD_LIBRARY_PATH=/usr/lib/${PRODUCT}:${LD_LIBRARY_PATH}
-        LD_LIBRARY_PATH=/usr/lib/${PRODUCT}/${SUBSYSTEM}:${LD_LIBRARY_PATH}
-        export LD_LIBRARY_PATH
+        JAVA="/usr/jdk/instances/jdk1.5.0/jre/bin/java"
+        JAVA_OPTIONS=""
 
-        PATH=/usr/bin
-        PATH=/usr/lib/${PRODUCT}:${PATH}
-        PATH=/usr/lib/${PRODUCT}/${SUBSYSTEM}:${PATH}
-        export PATH
-    elif [ "${ARCHITECTURE}" = "sparcv9" ] ; then
         LD_LIBRARY_PATH=/usr/lib:/lib
         LD_LIBRARY_PATH=/usr/lib/dirsec:${LD_LIBRARY_PATH}
         LD_LIBRARY_PATH=/usr/lib/${PRODUCT}:${LD_LIBRARY_PATH}
-        LD_LIBRARY_PATH=/usr/lib/${PRODUCT}/${SUBSYSTEM}:${LD_LIBRARY_PATH}
+        export LD_LIBRARY_PATH
+    elif [ "${ARCHITECTURE}" = "sparcv9" ] ; then
+        JAVA="/usr/jdk/instances/jdk1.5.0/jre/bin/java"
+        JAVA_OPTIONS="-d64"
+
+        LD_LIBRARY_PATH=/usr/lib:/lib
+        LD_LIBRARY_PATH=/usr/lib/dirsec:${LD_LIBRARY_PATH}
+        LD_LIBRARY_PATH=/usr/lib/${PRODUCT}:${LD_LIBRARY_PATH}
         LD_LIBRARY_PATH=/usr/lib/sparcv9:/lib/sparcv9:${LD_LIBRARY_PATH}
         LD_LIBRARY_PATH=/usr/lib/sparcv9/dirsec:${LD_LIBRARY_PATH}
         LD_LIBRARY_PATH=/usr/lib/sparcv9/${PRODUCT}:${LD_LIBRARY_PATH}
-        LD_LIBRARY_PATH=/usr/lib/sparcv9/${PRODUCT}/${SUBSYSTEM}:${LD_LIBRARY_PATH}
         export LD_LIBRARY_PATH
-
-        PATH=/usr/bin/sparcv9
-        PATH=/usr/lib/${PRODUCT}:${PATH}
-        PATH=/usr/lib/${PRODUCT}/${SUBSYSTEM}:${PATH}
-        PATH=/usr/lib/sparcv9/${PRODUCT}:${PATH}
-        PATH=/usr/lib/sparcv9/${PRODUCT}/${SUBSYSTEM}:${PATH}
-        export PATH
     else
         invalid_architecture "${ARCHITECTURE}"
         exit 255
@@ -146,24 +124,54 @@ fi
 
 
 ###############################################################################
-##  (4) Execute the binary executable specified by this command wrapper      ##
-##      based upon the preset LD_LIBRARY_PATH and PATH environment variables.##
+##  (5) Set the CP environment variable to determine the search              ##
+##      order this command wrapper uses to find jar files.                   ##
 ###############################################################################
 
-ORIGINAL_IFS=${IFS}
-IFS=:
+CP=/usr/lib/java/jss4.jar
+CP=/usr/lib/java/dirsec/jss4.jar:${CP}
+CP=/usr/lib/java/osutil.jar:${CP}
+CP=/usr/lib/java/dirsec/osutil.jar:${CP}
+CP=/usr/share/java/ldapjdk.jar:${CP}
+CP=/usr/share/java/${PRODUCT}/pki-nsutil.jar:${CP}
+CP=/usr/share/java/${PRODUCT}/pki-cmsutil.jar:${CP}
+CP=/usr/share/java/${PRODUCT}/pki-tools.jar:${CP}
+export CP
 
-for dir in ${PATH}
-do
-    if [ -x ${dir}/${COMMAND} ]
+
+###############################################################################
+##  (6) Execute the java command specified by this java command wrapper      ##
+##      based upon the preset LD_LIBRARY_PATH and CP environment variables.  ##
+###############################################################################
+
+if [ $# -eq 1 ] ||
+   [ $# -eq 2 ] ||
+   [ $# -eq 3 ]
+then
+    if [ "$1" = "-simpleinfo" ]
     then
-        IFS=${ORIGINAL_IFS}
-        ${dir}/${COMMAND} "$@"
-        exit $?
+        file $2 | grep 'ASCII text' > /dev/null
+        if [ $? -ne 0 ] ; then
+            ${JAVA} ${JAVA_OPTIONS} -cp ${CP} com.netscape.cmstools.${COMMAND}
+            printf "\n"
+            printf " ERROR:  '$2' is not an ASCII file!\n\n"
+            printf "         First, use 'BtoA $2 $2.b64'\n"
+            printf "         to convert a binary file into an ASCII file.\n\n"
+            exit 255
+        fi
+    else
+        file $1 | grep 'ASCII text' > /dev/null
+        if [ $? -ne 0 ] ; then
+            ${JAVA} ${JAVA_OPTIONS} -cp ${CP} com.netscape.cmstools.${COMMAND}
+            printf "\n"
+            printf " ERROR:  '$1' is not an ASCII file!\n\n"
+            printf "         First, use 'BtoA $1 $1.b64'\n"
+            printf "         to convert a binary file into an ASCII file.\n\n"
+            exit 255
+        fi
     fi
-done
+fi
 
-echo "Unable to find \"${COMMAND}\" in \"${PATH}\"!"
-
-exit 255
+${JAVA} ${JAVA_OPTIONS} -cp ${CP} com.netscape.cmstools.${COMMAND} "$@"
+exit $?
 
diff --git a/pki/base/java-tools/templates/pretty_print_crl_command_wrapper.in b/pki/base/java-tools/templates/pretty_print_crl_command_wrapper.in
--- a/pki/base/java-tools/templates/pretty_print_crl_command_wrapper.in
+++ b/pki/base/java-tools/templates/pretty_print_crl_command_wrapper.in
@@ -32,8 +32,8 @@ fi
 ##  (1) Specify variables used by this script.                               ##
 ###############################################################################
 
-PRODUCT=[PKI_PRODUCT]
-COMMAND=[PKI_COMMAND]
+PRODUCT=@PKI_PRODUCT@
+COMMAND=@PKI_COMMAND@
 
 
 ###############################################################################
@@ -143,6 +143,20 @@ export CP
 ##  (6) Execute the java command specified by this java command wrapper      ##
 ##      based upon the preset LD_LIBRARY_PATH and CP environment variables.  ##
 ###############################################################################
+
+if [ $# -eq 1 ] ||
+   [ $# -eq 2 ]
+then
+    file $1 | grep 'ASCII text' > /dev/null
+    if [ $? -ne 0 ] ; then
+        ${JAVA} ${JAVA_OPTIONS} -cp ${CP} com.netscape.cmstools.${COMMAND}
+        printf "\n"
+        printf "ERROR:  '$1' is not an ASCII file!\n\n"
+        printf "        First, use 'BtoA $1 $1.b64'\n"
+        printf "        to convert a binary file into an ASCII file.\n\n"
+        exit 255
+    fi
+fi
 
 ${JAVA} ${JAVA_OPTIONS} -cp ${CP} com.netscape.cmstools.${COMMAND} "$@"
 exit $?
