Added check for pki-server-nuxwdog parameter
Partially fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1353245

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

diff --git a/base/server/sbin/pki-server-nuxwdog b/base/server/sbin/pki-server-nuxwdog
--- a/base/server/sbin/pki-server-nuxwdog
+++ b/base/server/sbin/pki-server-nuxwdog
@@ -1,8 +1,18 @@
 #!/bin/sh
 
+if [ "$#" -ne 1 ]; then
+    echo "ERROR: $0 requires parameter"
+    exit 1
+fi
+
 . /etc/tomcat/tomcat.conf
 NAME=$1
-. /etc/sysconfig/$NAME
+if [ -f /etc/sysconfig/$NAME ]; then
+    . /etc/sysconfig/$NAME
+else
+    echo "ERROR: Unable to find /etc/sysconfig/$NAME file"
+    exit 1
+fi
 . /usr/libexec/tomcat/preamble
 
 NUXWDOG_PID=${CATALINA_BASE}/logs/wd-$NAME.pid
