Update development spec file templates
Version: 10.5.0
Release: 0.0.<timestamp>.<git commit ID>

The release number is composed as '0.0.<timestamp>.<git commit ID>'
to allow seamless updating where:

    * the initial ‘0’ is equivalent the previous official release
      number (‘0’ prior to any official releases); allows update
      from a development release to an official release
    * the ‘0.0’ is equivalent to the previous stage release
      number (‘0.0’ prior to any stage releases); allows update
      from a development release to a stage release
    * the ‘0.0.<timestamp>’ is required to be able to update one
      development release to another development release since
      there is no guarantee that the  <git commit ID> at
      development build time is greater than that of a development
      build that may already be installed on the system

Change-Id: Iad8d63eaa6437a9a48f99a46a4e209fd91b61ba9

diff --git a/scripts/compose_functions b/scripts/compose_functions
--- a/scripts/compose_functions
+++ b/scripts/compose_functions
@@ -126,6 +126,144 @@ Usage()
 
 
 ##
+## Extract Release Information from Specified Spec File
+##
+
+extract_release_information()
+{
+	if [ $# -ne 1 ] ; then
+		Usage
+		exit 255
+	fi
+
+	local pki_spec_file=$1
+
+	if [ ! -f ${pki_spec_file} ] ; then
+		printf "ERROR:  '${pki_spec_file}' is missing!\n\n"
+		Usage
+		exit 255
+	fi
+
+	if [ "${DISTRIBUTION}" = "Fedora " ] ; then
+		release_marker="fedora_release"
+		stage_marker="fedora_stage"
+	elif [ "${DISTRIBUTION}" = "Red Hat" ] ; then
+		release_marker="redhat_release"
+		stage_marker="redhat_stage"
+	fi
+
+	exec < ${pki_spec_file}
+	while read line; do
+		entry=`echo $line | cut -d: -f 1`
+		if [ "${entry:8:14}" = "${release_marker}" ] ; then
+			default_release_value=`echo $line | cut -d' ' -f 3`
+		elif [ "${entry:8:12}" = "${stage_marker}" ] ; then
+			default_stage_value=`echo $line | cut -d' ' -f 3`
+		fi
+	done
+}
+
+##
+## Compute Release Information
+##
+##
+##      Examples:
+##
+##          # script -c "pki/scripts/compose_dogtag_pki_meta_packages rpms"
+##          # ls packages/SRPMS
+##          dogtag-pki-10.5.0-0.0.20170829113408.6d23ffdd.fc27.src.rpm
+##
+##          # script -c "USE_TIMESTAMP=1 USE_GIT_COMMIT_ID=1
+##            pki/scripts/compose_dogtag_pki_meta_packages rpms"
+##          # ls packages/SRPMS
+##          dogtag-pki-10.5.0-0.0.20170829113604.6d23ffdd.fc27.src.rpm
+##
+##          # script -c "USE_STAGE=0 USE_TIMESTAMP=0 USE_GIT_COMMIT_ID=0
+##            pki/scripts/compose_dogtag_pki_meta_packages rpms"
+##          # ls packages/SRPMS
+##          dogtag-pki-10.5.0-0.fc27.src.rpm
+##
+##          # script -c "USE_TIMESTAMP=0 USE_GIT_COMMIT_ID=0
+##            pki/scripts/compose_dogtag_pki_meta_packages rpms"
+##          # ls packages/SRPMS
+##          dogtag-pki-10.5.0-0.0.fc27.src.rpm
+##
+##          # script -c "USE_TIMESTAMP=1 USE_GIT_COMMIT_ID=0
+##            pki/scripts/compose_dogtag_pki_meta_packages rpms"
+##          # ls packages/SRPMS
+##          dogtag-pki-10.5.0-0.0.20170829113859.fc27.src.rpm
+##
+##          # script -c "USE_TIMESTAMP=0 USE_GIT_COMMIT_ID=1
+##            pki/scripts/compose_dogtag_pki_meta_packages rpms"
+##          # ls packages/SRPMS
+##          dogtag-pki-10.5.0-0.0.6d23ffdd.fc27.src.rpm
+##
+
+compute_release_information()
+{
+	if [ $# -ne 1 ] ; then
+		Usage
+		exit 255
+	fi
+
+	local pki_spec_file=$1
+
+	if [ ! -f ${pki_spec_file} ] ; then
+		printf "ERROR:  '${pki_spec_file}' is missing!\n\n"
+		Usage
+		exit 255
+	fi
+
+	# Set USE_PKI_RELEASE=1
+	export USE_PKI_RELEASE=1
+
+	# Obtain relevant values from the spec file of the specified package
+	extract_release_information ${pki_spec_file}
+
+	# Always apply the official release value in ${default_release_value}
+	printf "Setting 'default_release_value=${default_release_value}'\n"
+	PKI_RELEASE=${default_release_value}
+
+	# Optionally apply the stage release value in ${default_stage_value}
+	if [ -n ${USE_STAGE} ] && [ "${USE_STAGE}" = "0" ]; then
+		printf "unset USE_STAGE\n"
+		unset USE_STAGE
+	else
+		# By default, append a stage to the release designation
+		printf "Setting 'default_stage_value=${default_stage_value}'\n"
+		PKI_RELEASE=${PKI_RELEASE}.${default_stage_value}
+	fi
+
+	# Optionally compute a timestamp
+	if [ -n ${USE_TIMESTAMP} ] && [ "${USE_TIMESTAMP}" = "0" ]; then
+		printf "unset USE_TIMESTAMP\n"
+		unset USE_TIMESTAMP
+	else
+		# By default, append a timestamp to the release designation
+		now=`date +"%Y%m%d%H%M%S"`
+		timestamp=`printf "%.14s" ${now}`
+		printf "Setting 'timestamp=${timestamp}'\n"
+		PKI_RELEASE=${PKI_RELEASE}.${timestamp}
+	fi
+
+	# Optionally fetch the git commit ID from the source repository
+	if [ -n ${USE_GIT_COMMIT_ID} ] && [ "${USE_GIT_COMMIT_ID}" = "0" ]; then
+		printf "unset USE_GIT_COMMIT_ID\n"
+		unset USE_GIT_COMMIT_ID
+	else
+		# By default, append a git commit ID to the release designation
+		latest_git_commit_id=`git -C ${COMPOSE_PWD}/.. rev-parse --short=8 HEAD`
+		git_commit_id=`printf "%.8s" ${latest_git_commit_id}`
+		printf "Setting 'git_commit_id=${git_commit_id}'\n"
+		PKI_RELEASE=${PKI_RELEASE}.${git_commit_id}
+	fi
+
+	printf "Setting 'PKI_RELEASE=${PKI_RELEASE}'\n"
+	export PKI_RELEASE
+}
+
+
+##
 ## Copy Specified Patches to SOURCES
 ##
 Fetch_Patch_Files()
