Add reindex step for setting up ACME database
As described in issue #5160 with LMDB backend newly added DS
indexes always need to be rebuilt. For ACME and other subsystems
installed without pkispawn this additional step needs to be done
manually. In the future this step can be integrated into pkispawn
for ACME.

Some ACME tests have been modified to create DS instances with
LMDB backend to demonstrate the additional reindex step. The ACME
docs have been updated as well.

https://github.com/dogtagpki/pki/issues/5160

diff --git a/.github/workflows/acme-separate-test.yml b/.github/workflows/acme-separate-test.yml
--- a/.github/workflows/acme-separate-test.yml
+++ b/.github/workflows/acme-separate-test.yml
@@ -3,7 +3,10 @@ name: ACME on separate instance
 on: workflow_call
 
 env:
-  DS_IMAGE: ${{ vars.DS_IMAGE || 'quay.io/389ds/dirsrv' }}
+  # use pki-runner image by default to create DS with LMDB
+  # backend which requires rebuilding the indexes:
+  # https://github.com/dogtagpki/pki/issues/5160
+  DS_IMAGE: ${{ vars.DS_IMAGE || 'pki-runner' }}
 
 jobs:
   # docs/installation/acme/Installing_PKI_ACME_Responder.md
@@ -38,6 +41,19 @@ jobs:
               --network=example \
               --network-alias=cads.example.com \
               cads
+
+          docker exec cads dsconf \
+              localhost \
+              backend \
+              config \
+              get \
+              | tee output
+
+          # CA DS backend should be LMDB
+          echo "nsslapd-backend-implement: mdb" > expected
+          cat output | sed -n "/^nsslapd-backend-implement:/p" > actual
+
+          diff expected actual
 
       - name: Set up CA container
         run: |
@@ -91,6 +107,19 @@ jobs:
               --network-alias=acmeds.example.com \
               acmeds
 
+          docker exec acmeds dsconf \
+              localhost \
+              backend \
+              config \
+              get \
+              | tee output
+
+          # ACME DS backend should be LMDB
+          echo "nsslapd-backend-implement: mdb" > expected
+          cat output | sed -n "/^nsslapd-backend-implement:/p" > actual
+
+          diff expected actual
+
       - name: Set up ACME container
         run: |
           tests/bin/runner-init.sh \
@@ -101,16 +130,23 @@ jobs:
 
       - name: Set up ACME database
         run: |
+          # import ACME schema
           docker exec acme ldapmodify \
               -H ldap://acmeds.example.com:3389 \
               -D "cn=Directory Manager" \
               -w Secret.123 \
               -f /usr/share/pki/acme/database/ds/schema.ldif
+
+          # create ACME indexes
           docker exec acme ldapadd \
               -H ldap://acmeds.example.com:3389 \
               -D "cn=Directory Manager" \
               -w Secret.123 \
               -f /usr/share/pki/acme/database/ds/index.ldif
+
+          # rebuild ACME indexes later
+
+          # create ACME subtree
           docker exec acme ldapadd \
               -H ldap://acmeds.example.com:3389 \
               -D "cn=Directory Manager" \
@@ -127,6 +163,7 @@ jobs:
 
       - name: Install ACME
         run: |
+          # TODO: update pkispawn to set up ACME database and realm
           docker exec acme pkispawn \
               -f /usr/share/pki/server/examples/installation/acme.cfg \
               -s ACME \
@@ -400,7 +437,57 @@ jobs:
               --server http://acme.example.com:8080/acme/directory \
               --email testuser@example.com \
               --agree-tos \
+              --non-interactive \
+              > >(tee stdout) 2> >(tee stderr >&2) || true
+
+          # registration should fail since ACME indexes has not been rebuilt
+          echo "acme.errors.ClientError: <Response [500]>" > expected
+          cat stderr | sed -n '/^acme.errors.ClientError:/p' > actual
+
+          diff expected actual
+
+      - name: Rebuild ACME indexes
+        run: |
+          # LMDB indexes must be rebuilt
+          docker exec acme ldapadd \
+              -H ldap://acmeds.example.com:3389 \
+              -D "cn=Directory Manager" \
+              -w Secret.123 \
+              -f /usr/share/pki/acme/database/ds/indextask.ldif
+
+          # wait for rebuild to complete
+          while true; do
+              sleep 1
+
+              docker exec acme ldapsearch \
+                  -H ldap://acmeds.example.com:3389 \
+                  -D "cn=Directory Manager" \
+                  -w Secret.123 \
+                  -b "cn=acme,cn=index,cn=tasks,cn=config" \
+                  -LLL \
+                  nsTaskExitCode \
+                  | tee output
+
+              sed -n -e 's/nsTaskExitCode:\s*\(.*\)/\1/p' output > nsTaskExitCode
+              cat nsTaskExitCode
+
+              if [ -s nsTaskExitCode ]; then
+                  break
+              fi
+          done
+
+          echo "0" > expected
+          diff expected nsTaskExitCode
+
+      - name: Register ACME account again
+        run: |
+          docker exec client certbot register \
+              --server http://acme.example.com:8080/acme/directory \
+              --email testuser@example.com \
+              --agree-tos \
               --non-interactive
+
+          # registration should work
 
       - name: Check ACME accounts after registration
         run: |
