Fix incorrect default signing algorithm
The PKIDeployer.update_system_cert() was incorrectly setting
the default signing algorithm param in CS.cfg for all certs
using the key algorithm param in pkispawn which could cause
a problem if the key algorithm and signing algorithm are not
the same.

The code has been modified to set the param properly using
the signing algorithm param in pkispawn for CA/OCSP/audit
signing certs only. This param is not used by other certs so
it does not need to be set for those certs.

The pki-server ca-config-show CLI has been updated to return
a non-zero code if the param being requested doesn't exist.

The tests have been updated to use different key and signing
algorithms.

https://github.com/dogtagpki/pki/issues/4518

diff --git a/.github/workflows/ca-rsa-pss-test.yml b/.github/workflows/ca-rsa-pss-test.yml
--- a/.github/workflows/ca-rsa-pss-test.yml
+++ b/.github/workflows/ca-rsa-pss-test.yml
@@ -50,24 +50,22 @@ jobs:
       - name: Connect PKI container to network
         run: docker network connect example pki --alias pki.example.com
 
-      - name: Install CA with SHA512withRSA/PSS
+      - name: Install CA
         run: |
           docker exec pki pkispawn \
               -f /usr/share/pki/server/examples/installation/ca.cfg \
               -s CA \
               -D pki_ds_url=ldap://ds.example.com:3389 \
               -D pki_use_pss_rsa_signing_algorithm=True \
-              -D pki_ca_signing_key_algorithm=SHA512withRSA/PSS \
+              -D pki_ca_signing_key_algorithm=SHA384withRSA/PSS \
               -D pki_ca_signing_signing_algorithm=SHA512withRSA/PSS \
-              -D pki_ocsp_signing_key_algorithm=SHA512withRSA/PSS \
-              -D pki_ocsp_signing_signing_algorithm=SHA512withRSA/PSS \
-              -D pki_audit_signing_key_algorithm=SHA512withRSA/PSS \
-              -D pki_audit_signing_signing_algorithm=SHA512withRSA/PSS \
-              -D pki_subsystem_key_algorithm=SHA512withRSA/PSS \
-              -D pki_subsystem_signing_algorithm=SHA512withRSA/PSS \
-              -D pki_sslserver_key_algorithm=SHA512withRSA/PSS \
-              -D pki_sslserver_signing_algorithm=SHA512withRSA/PSS \
-              -D pki_admin_key_algorithm=SHA512withRSA/PSS \
+              -D pki_ocsp_signing_key_algorithm=SHA384withRSA/PSS \
+              -D pki_ocsp_signing_signing_algorithm=SHA384withRSA/PSS \
+              -D pki_audit_signing_key_algorithm=SHA384withRSA/PSS \
+              -D pki_audit_signing_signing_algorithm=SHA384withRSA/PSS \
+              -D pki_subsystem_key_algorithm=SHA384withRSA/PSS \
+              -D pki_sslserver_key_algorithm=SHA384withRSA/PSS \
+              -D pki_admin_key_algorithm=SHA384withRSA/PSS \
               -D pki_cert_id_generator=random \
               -D pki_request_id_generator=random \
               -v
@@ -137,8 +135,8 @@ jobs:
           sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
           diff expected actual
 
-          # default signing algorithm should be "SHA512withRSA/PSS"
-          echo "SHA512withRSA/PSS" > expected
+          # default signing algorithm should be "SHA384withRSA/PSS"
+          echo "SHA384withRSA/PSS" > expected
           docker exec pki pki-server ca-config-show ca.ocsp_signing.defaultSigningAlgorithm | tee actual
           diff expected actual
 
@@ -161,8 +159,8 @@ jobs:
           sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
           diff expected actual
 
-          # default signing algorithm should be "SHA512withRSA/PSS"
-          echo "SHA512withRSA/PSS" > expected
+          # default signing algorithm should be "SHA384withRSA/PSS"
+          echo "SHA384withRSA/PSS" > expected
           docker exec pki pki-server ca-config-show ca.audit_signing.defaultSigningAlgorithm | tee actual
           diff expected actual
 
@@ -185,10 +183,11 @@ jobs:
           sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
           diff expected actual
 
-          # default signing algorithm should be "SHA512withRSA/PSS"
-          echo "SHA512withRSA/PSS" > expected
-          docker exec pki pki-server ca-config-show ca.subsystem.defaultSigningAlgorithm | tee actual
-          diff expected actual
+          # default signing algorithm should not exist
+          echo "ERROR: No such parameter: ca.subsystem.defaultSigningAlgorithm" > expected
+          docker exec pki pki-server ca-config-show ca.subsystem.defaultSigningAlgorithm \
+              > >(tee stdout) 2> >(tee stderr >&2) || true
+          diff expected stderr
 
       - name: Check SSL server cert
         run: |
@@ -209,10 +208,11 @@ jobs:
           sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
           diff expected actual
 
-          # default signing algorithm should be "SHA512withRSA/PSS"
-          echo "SHA512withRSA/PSS" > expected
-          docker exec pki pki-server ca-config-show ca.sslserver.defaultSigningAlgorithm | tee actual
-          diff expected actual
+          # default signing algorithm should not exist
+          echo "ERROR: No such parameter: ca.sslserver.defaultSigningAlgorithm" > expected
+          docker exec pki pki-server ca-config-show ca.sslserver.defaultSigningAlgorithm \
+              > >(tee stdout) 2> >(tee stderr >&2) || true
+          diff expected stderr
 
       - name: Run PKI healthcheck
         run: docker exec pki pki-healthcheck --failures-only
