Update EST test for CSR subject check

diff --git a/.github/workflows/est-ds-realm-test.yml b/.github/workflows/est-ds-realm-test.yml
--- a/.github/workflows/est-ds-realm-test.yml
+++ b/.github/workflows/est-ds-realm-test.yml
@@ -242,8 +242,8 @@ jobs:
           objectClass: inetOrgPerson
           objectClass: cmsuser
           uid: est-test-user
-          sn: EST TEST USER
-          cn: EST TEST USER
+          sn: test.example.com
+          cn: test.example.com
           usertype: undefined
           userPassword: Secret.123
           EOF
@@ -283,6 +283,16 @@ jobs:
           echo "subject=CN=test.example.com" > expected
           diff expected actual
 
+      - name: Enroll new certificate with certificate but using different CN
+        run: |
+          docker exec pki mkdir new_certs0
+          docker exec -e EST_OPENSSL_CACERT=cacert.pem pki estclient -e -s pki.example.com -p 8443 \
+              --common-name test-new.example.com -o ./new_certs0 -u est-test-user -h Secret.123 | tee output || true
+
+          # Request should fails with authorization error (status code 403)
+          STATUS=$(cat output  | sed -nE 's/.* HTTP response HTTP\/1.1 ([[:digit:]]*).*$/\1/p')
+          [ "$STATUS" == "403" ]
+
       - name: Add certificate to the user
         run: |
           VERSION=$(docker exec pki PrettyPrintCert cert.pem | sed -n 's/\s*Version:\s*v3/2/p')
@@ -308,13 +318,13 @@ jobs:
 
       - name: Enroll new certificate with certificate
         run: |
-          docker exec pki mkdir new_certs
+          docker exec pki mkdir new_certs1
           docker exec -e EST_OPENSSL_CACERT=cacert.pem pki estclient -e -s pki.example.com -p 8443 \
-              --common-name test.example.com -o ./new_certs -c cert.pem -k key-x-x.pem
+              --common-name test.example.com -o ./new_certs1 -c cert.pem -k key-x-x.pem
 
-          docker exec pki openssl base64 -d --in new_certs/cert-0-0.pkcs7 --out new_certs/cert-0-0.pkcs7.der
-          docker exec pki openssl pkcs7 -in new_certs/cert-0-0.pkcs7.der -inform DER -print_certs -quiet -out new_certs/cert.pem
-          docker exec pki openssl x509 -in new_certs/cert.pem -subject -noout | tee actual
+          docker exec pki openssl base64 -d --in new_certs1/cert-0-0.pkcs7 --out new_certs1/cert-0-0.pkcs7.der
+          docker exec pki openssl pkcs7 -in new_certs1/cert-0-0.pkcs7.der -inform DER -print_certs -quiet -out new_certs1/cert.pem
+          docker exec pki openssl x509 -in new_certs1/cert.pem -subject -noout | tee actual
           echo "subject=CN=test.example.com" > expected
           diff expected actual
 
@@ -336,6 +346,7 @@ jobs:
           docker exec -e EST_OPENSSL_CACERT=cacert.pem pki estclient -e -s pki.example.com -p 8443 \
               --common-name test-new.example.com -o ./new_certs2 -c cert.pem -k key-x-x.pem | tee output || true
 
+          # Request should fails with authorization error (status code 403)
           STATUS=$(cat output  | sed -nE 's/.* HTTP response HTTP\/1.1 ([[:digit:]]*).*$/\1/p')
           [ "$STATUS" == "403" ]
 
@@ -347,15 +358,27 @@ jobs:
 
           docker exec pki pki-server restart --wait
 
-      - name: Enroll new certificate with certificate but using different subject and check disabled
+      - name: Enroll certificate with user/password but using different subject and check disabled
         run: |
           docker exec pki mkdir new_certs3
           docker exec -e EST_OPENSSL_CACERT=cacert.pem pki estclient -e -s pki.example.com -p 8443 \
-              --common-name test-new.example.com -o ./new_certs3 -c cert.pem -k key-x-x.pem
+              --common-name test-new.example.com -o new_certs3 -u est-test-user -h Secret.123
 
           docker exec pki openssl base64 -d --in new_certs3/cert-0-0.pkcs7 --out new_certs3/cert-0-0.pkcs7.der
           docker exec pki openssl pkcs7 -in new_certs3/cert-0-0.pkcs7.der -inform DER -print_certs -quiet -out new_certs3/cert.pem
           docker exec pki openssl x509 -in new_certs3/cert.pem -subject -noout | tee actual
+          echo "subject=CN=test-new.example.com" > expected
+          diff expected actual
+
+      - name: Enroll new certificate with certificate but using different subject and check disabled
+        run: |
+          docker exec pki mkdir new_certs4
+          docker exec -e EST_OPENSSL_CACERT=cacert.pem pki estclient -e -s pki.example.com -p 8443 \
+              --common-name test-new.example.com -o ./new_certs4 -c cert.pem -k key-x-x.pem
+
+          docker exec pki openssl base64 -d --in new_certs4/cert-0-0.pkcs7 --out new_certs4/cert-0-0.pkcs7.der
+          docker exec pki openssl pkcs7 -in new_certs4/cert-0-0.pkcs7.der -inform DER -print_certs -quiet -out new_certs4/cert.pem
+          docker exec pki openssl x509 -in new_certs4/cert.pem -subject -noout | tee actual
           echo "subject=CN=test-new.example.com" > expected
           diff expected actual
 
diff --git a/.github/workflows/est-postgresql-realm-test.yml b/.github/workflows/est-postgresql-realm-test.yml
--- a/.github/workflows/est-postgresql-realm-test.yml
+++ b/.github/workflows/est-postgresql-realm-test.yml
@@ -315,7 +315,7 @@ jobs:
         run: |
           DIGEST=$(docker exec pki tomcat-digest Secret.123 | sed 's/.*://')
 
-          docker exec postgresql psql -U est -t -A -c "INSERT INTO users VALUES ('est-test-user', 'EST TEST USER', '$DIGEST');"  est
+          docker exec postgresql psql -U est -t -A -c "INSERT INTO users VALUES ('est-test-user', 'test.example.com', '$DIGEST');"  est
           docker exec postgresql psql -U est -t -A -c "INSERT INTO group_members VALUES ('EST Users', 'est-test-user');"  est
 
       - name: Install est client
@@ -333,6 +333,16 @@ jobs:
           docker exec pki openssl x509 -in cert.pem -subject -noout | tee actual
           echo "subject=CN=test.example.com" > expected
           diff expected actual
+
+      - name: Enroll new certificate with certificate but using different CN
+        run: |
+          docker exec pki mkdir new_certs0
+          docker exec -e EST_OPENSSL_CACERT=cacert.pem pki estclient -e -s pki.example.com -p 8443 \
+              --common-name test-new.example.com -o ./new_certs0 -u est-test-user -h Secret.123 | tee output || true
+
+          # Request should fails with authorization error (status code 403)
+          STATUS=$(cat output  | sed -nE 's/.* HTTP response HTTP\/1.1 ([[:digit:]]*).*$/\1/p')
+          [ "$STATUS" == "403" ]
 
       - name: Add certificate to the user
         run: |
@@ -383,6 +393,7 @@ jobs:
           docker exec -e EST_OPENSSL_CACERT=cacert.pem pki estclient -e -s pki.example.com -p 8443 \
               --common-name test-new.example.com -o ./new_certs2 -c cert.pem -k key-x-x.pem | tee output || true
 
+          # Request should fails with authorization error (status code 403)
           STATUS=$(cat output  | sed -nE 's/.* HTTP response HTTP\/1.1 ([[:digit:]]*).*$/\1/p')
           [ "$STATUS" == "403" ]
 
@@ -394,15 +405,27 @@ jobs:
 
           docker exec pki pki-server restart --wait
 
-      - name: Enroll new certificate with certificate but using different subject and check disabled
+      - name: Enroll certificate with user/password but using different subject and check disabled
         run: |
           docker exec pki mkdir new_certs3
           docker exec -e EST_OPENSSL_CACERT=cacert.pem pki estclient -e -s pki.example.com -p 8443 \
-              --common-name test-new.example.com -o ./new_certs3 -c cert.pem -k key-x-x.pem
+              --common-name test-new.example.com -o new_certs3 -u est-test-user -h Secret.123
 
           docker exec pki openssl base64 -d --in new_certs3/cert-0-0.pkcs7 --out new_certs3/cert-0-0.pkcs7.der
           docker exec pki openssl pkcs7 -in new_certs3/cert-0-0.pkcs7.der -inform DER -print_certs -quiet -out new_certs3/cert.pem
           docker exec pki openssl x509 -in new_certs3/cert.pem -subject -noout | tee actual
+          echo "subject=CN=test-new.example.com" > expected
+          diff expected actual
+
+      - name: Enroll new certificate with certificate but using different subject and check disabled
+        run: |
+          docker exec pki mkdir new_certs4
+          docker exec -e EST_OPENSSL_CACERT=cacert.pem pki estclient -e -s pki.example.com -p 8443 \
+              --common-name test-new.example.com -o ./new_certs4 -c cert.pem -k key-x-x.pem
+
+          docker exec pki openssl base64 -d --in new_certs4/cert-0-0.pkcs7 --out new_certs4/cert-0-0.pkcs7.der
+          docker exec pki openssl pkcs7 -in new_certs4/cert-0-0.pkcs7.der -inform DER -print_certs -quiet -out new_certs4/cert.pem
+          docker exec pki openssl x509 -in new_certs4/cert.pem -subject -noout | tee actual
           echo "subject=CN=test-new.example.com" > expected
           diff expected actual
 
